//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_People
    {
        public int User_ID { get; set; }
        public int Role_ID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool ACTIVE { get; set; }
        public string UserStartDate { get; set; }
        public Nullable<byte> UserGender { get; set; }
        public string Status { get; set; }
        public string Gender { get; set; }
    }
}
